baseURL = "https://corner0530.github.io/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "corner0530.github.io"
theme = "ananke"

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
Name = "home"
URL = "/"
weight = 1

[[Menus.main]]
Name = "about"
URL = "/about"
weight = 1

[[params.ananke_socials]]
name = "github"
url = "https://github.com/corner0530"
